### ISSUE TITLE
Fluxo "Esqueceu sua senha"

### ISSUE THREAD

**Issue by zjefersound** [joaozenaro/park-hub#17]
- Criar interface
- Criar rotas
- Incluir métodos no auth service

Referências visuais: 
https://dribbble.com/shots/16848359-Reset-password-flow-Untitled-UI

**Comment by joaozenaro** [comment]
Dei uma olhada e acredito que encontrei uma forma legal de fazer essa parada.

# Etapas

1. Request para `/api/v1/request-password-reset`
Em uma rota autenticada, com o token JWT, o usuario simplesmente faz um GET request para a rota, que no backend é possivel ver de quem é o token, e enviar o email pra essa pessoa.

2. Abrir o Email
Na caixa de email do usuario ele recebe um link, ao clicar no link ele é redirecionado para uma pagina especial do app. Essa pagina deve:
* Ler a query string e armazenar o token que foi enviado
* Fornecer um input de senha e confirmação

3. Solicitar a troca de senha
Após entrar no aplicativo novamente e preencher a nova senha, um POST request para `/api/v1/request-password-reset` faz a troca de senha. O corpo da requisição deve conter o modelo para mapear no backend:
```
POST /api/v1/password-reset
{
    "PasswordReset": {
        "token": ...,
        "password": ...
    }
}
```
